[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
grime = "FwCfGNt8XdsFQy7X2N14Sod7gk8aAj5jB3Q7Bt6neZRe"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
